### PR TITLE
Add a guide for using apx on other distributions

### PR DESCRIPTION
**Pull request by CosmicFusion**

### CODE REVIEW

**Comment by delight-aug** [comment]
Please notice that you have wrote a guide to use `apx` on other *distributions*, in the same sentence with a guide to use another *package manager*. I'd like to point put other issues with this PR, but I have no idea whether it's welcomed in the first place. Before putting your work into something that may (or may not) be discarded, you should have opened an issue describing what you want to change.

But thanks for trying to help, anyway

**Comment by CosmicFusion** [comment]
there's this issue https://github.com/Vanilla-OS/apx/issues/5, but most of the stuff was done on the discord

**Comment by CosmicFusion** [comment]
> Please notice that you have wrote a guide to use `apx` on other _distributions_, in the same sentence with a guide to use another _package manager_. I'd like to point put other issues with this PR, but I have no idea whether it's welcomed in the first place. Before putting your work into something that may (or may not) be discarded, you should have opened an issue describing what you want to change.
> 
> But thanks for trying to help, anyway

ok i fixed both issues now i think...

**Comment by delight-aug** [comment]
To be honest, I feel like this guide is almost unnecessary. It was already written in the README that you can modify `config.json`. And fields of the config are already mostly self-explanatory. What I didn't understand immediately from the config is the `container` section. Yet, this guide only vaguely describes one of its fields. Other then that the only new thing this guide explains is the fact that you can modify the installed config.

**Comment by CosmicFusion** [comment]
I mean yeah i only added the package manager guide for completeness, but i had to wait months to get mirko to spit out what should be put in the container image, and that means this change is required and they are not self explanatory, also more detailed documentation wouldn't hurt would it?

________________________________

**Comment by PureTryOut** [comment]
Note that if #38 is merged, the config file will be changed (reduced) quite a bit.

**Comment by CosmicFusion** [comment]
ok since https://github.com/Vanilla-OS/apx/pull/38 got merged, i will close this pull request as it is no longer required, i'll wait for https://github.com/Vanilla-OS/apx/pull/37 to be merged and see if that needs changes in the README again.

**Pull request closed without merging**
