### PR TITLE
Make apx more portable

### PR DESCRIPTION
**Pull request by PureTryOut**
apx currently uses non-standard commands like `which` and `lsb_release`, this PR replaces them for more portable alternatives.

**Replace 'which' usage for the more standard 'command -v'**

'which' is actually a Debianism, which just happens to be available in
most distros. 'command -v' is actually the standard way to check if a
tool exists in $PATH

**Use /etc/os-release rather than lsb_release to detect the OS**

lsb_release is not something that is installed on every distro, but
/etc/os-release is. So use that to detect the host system rather than
lsb_release

### CODE REVIEW

**Review by bketelsen — APPROVED** [review]
This is a great change thank you.

**Review by kbdharun — APPROVED** [review]

**Comment by PureTryOut** [comment]
Uh, why are you adding commits to my branch? 😢

**Comment by mirkobrombin** [comment]
> Uh, why are you adding commits to my branch? cry

there were some conflicts and some necessary changes, i didn't want to bother you haha, sorry. I can mention you next time if you feel comfortable. Also, would you like to join the Discord conversation?

**Comment by PureTryOut** [comment]
Sorry I don't use proprietary platforms when I can help it, especially not centralized ones when there are federated alternatives like Matrix out there 😅

**Comment by mirkobrombin** [comment]
I'll ping you in the MR directly next time.

**Pull request merged**
