### PR TITLE
Update ro.yml

### PR DESCRIPTION
**Pull request by thednp**
* Make the language more friendly and more clear.
* Also fix line breaks via the use of "\" (backslash).

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
Thanks for your contribution., I will merge this PR to the old branch (`main`).

**Note**: With Apx v2 there are major changes with all these strings, translations for it can be done in Weblate at <https://hosted.weblate.org/projects/vanilla-os/apx/> with ease, as creating PRs manually with these files often lead to merge conflicts.

**Comment by thednp** [comment]
@kbdharun will look into it.

**Comment by thednp** [comment]
@kbdharun done.

**Comment by kbdharun** [comment]
> done. The work on Weblate is kinda slow IMO.

Great, yeah Weblate can be a bit slow based on your location.

**Pull request merged**
