### PR TITLE
README: Add community packages

### PR DESCRIPTION
**Pull request by dch82**
I added an install guide for Arch using the aur package
#167

### CODE REVIEW

**Comment by kbdharun** [comment]
I am not really sure about this PR, as the other package isn't officially made by us.

I would suggest making this section at last and naming it something like Community packages or something like that. And add a disclaimer that we don't have affiliation with it.

**Comment by dch82** [comment]
OK, I will do that.

**Comment by kbdharun** [comment]
I have a different idea for listing this, I will edit it directly here in an hour.

**Comment by kbdharun** [comment]
Now, that I think about it, Installation instructions should be in Wiki instead, I will enable it for apx repo as these are community packages. In tldr pages we have this https://github.com/tldr-pages/tldr/wiki/tldr-pages-clients maybe we can have something similar.

**Comment by dch82** [comment]
> Note: The reason why I marked this PR as a draft is that if you see my latest commit, repology lists another package "apx" too in the Fedora repo, which doesn't seem to be actively maintained, I have requested it to be renamed here https://repology.org/project/apx/report. Once, it is merged I will merge this PR.

That sounds cool: Instead of having to list installation instructions for _every single_ supported distro, we can just have a repology packaging badge and compilation instructions.

**Comment by kbdharun** [comment]
Good news the repology has dealt with our naming conflict and our is listed at https://repology.org/project/apx-package-manager/versions

**Review by kbdharun — APPROVED** [review]

**Pull request merged**
