### PR TITLE
fix:[#411] stacks update asks for new list of pkgs

### LINKED ISSUE #409: stacks packages update form doesnt update correctly
Updating a stack package list is unclear and doesn't appear to update the list appropriately.
```bash
apx stacks update noble
```
```
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  Do you want to confirm the current packages list? vim
       	 - neofetch
       	 - git
vim neofetch git
 INFO  Updated stack 'noble'.
```
```bash
apx stacks show noble
```
```
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name            ┊ noble        ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Base            ┊ ubuntu:noble ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Packages        ┊              ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Package manager ┊ apt          ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
```
```bash
apx stacks update noble
```
```
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  You have not provided any packages to install in the stack. Do you want to add some now?[y/N]
y
 INFO  Type the packages you want to install in the stack, separated by a space, or confirm the current ones (%s):
neofetch,vim,git
 INFO  Updated stack 'noble'.
```
```bash
apx stacks show noble
```
```
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name            ┊ noble            ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Base            ┊ ubuntu:noble     ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Packages        ┊ neofetch,vim,git ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Package manager ┊ apt              ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
```
```bash
apx stacks update noble
```
```
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  Do you want to confirm the current packages list? neofetch,vim,git
neofetch,vim    
 INFO  Updated stack 'noble'.
```
```bash
apx stacks show noble
```
```
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name            ┊ noble        ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Base            ┊ ubuntu:noble ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Packages        ┊              ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Package manager ┊ apt          ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
```

### LINKED ISSUE #411: update packages for stacks takes multiple update operations
In order to update a packages list for a stack, it requires two update operations.  One operation to remove the packages and another to add a new list

```
jardon@lagann:~/Projects/apx$ apx stacks show noble
error reading binaries: bufio.Scanner: token too long
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name            ┊ noble            ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Base            ┊ ubuntu:noble     ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Packages        ┊ vim,neofetch,git ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Package manager ┊ apt              ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
jardon@lagann:~/Projects/apx$ apx stacks update noble
error reading binaries: bufio.Scanner: token too long
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  Do you want to confirm the current packages list? vim,neofetch,git
y
 INFO  Updated stack 'noble'.
jardon@lagann:~/Projects/apx$ apx stacks show noble
error reading binaries: bufio.Scanner: token too long
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name            ┊ noble            ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Base            ┊ ubuntu:noble     ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Packages        ┊ vim,neofetch,git ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Package manager ┊ apt              ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
jardon@lagann:~/Projects/apx$ apx stacks update noble
error reading binaries: bufio.Scanner: token too long
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  Do you want to confirm the current packages list? vim,neofetch,git
n
 INFO  Updated stack 'noble'.
jardon@lagann:~/Projects/apx$ apx stacks show noble
error reading binaries: bufio.Scanner: token too long
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name            ┊ noble        ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Base            ┊ ubuntu:noble ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Packages        ┊              ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Package manager ┊ apt          ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
```

### PR DESCRIPTION
**Pull request by jardon**
this PR addresses both of the below issues in one sweep.  it reworks the prompting of the user for an update.

- stacks update asks if pkgs need to be updated
- takes a space-separated list of packages to replace

```
jardon@lagann:~/Projects/apx$ ./apx stacks update noble
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  You have not provided any packages to install in the stack. Do you want to add some now?[y/N]
y
 INFO  Type the packages you want to install in the stack, separated by a space:
neofetch vim
 INFO  Updated stack 'noble'.
jardon@lagann:~/Projects/apx$ ./apx stacks update noble
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  Do you want to update the list of packages?[y/N]
       	 - neofetch
       	 - vim
y
 INFO  Type the packages you want to install in the stack, separated by a space:
neofetch vim git
 INFO  Updated stack 'noble'.
jardon@lagann:~/Projects/apx$ ./apx stacks update noble
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  Do you want to update the list of packages?[y/N]
       	 - neofetch
       	 - vim
       	 - git
n
 INFO  Updated stack 'noble'.
jardon@lagann:~/Projects/apx$ ./apx stacks update noble
 INFO  Type a new base or confirm the current one (ubuntu:noble):

 INFO  Choose a new package manager or confirm the current one (apt):

 INFO  Do you want to update the list of packages?[y/N]
       	 - neofetch
       	 - vim
       	 - git
y
 INFO  Type the packages you want to install in the stack, separated by a space:

 INFO  Updated stack 'noble'.
jardon@lagann:~/Projects/apx$ ./apx stacks show noble
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Name            ┊ noble        ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Base            ┊ ubuntu:noble ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Packages        ┊              ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
┊ Package manager ┊ apt          ┊
┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼┄┄┄┄┄┄┄┄┄┄┄┄┄┄┼
```

closes #409 
closes #411

### CODE REVIEW

**Comment by jardon** [comment]
i will say, before this is approved and merged, the prompt doesn't make sense with the `-y` / `--assume-yes` option.  it would make more sense to me if the option was something along the lines of `--no-prompt`

**Comment by mirkobrombin** [comment]
Makes sense, I do agree with this

**Comment by jardon** [comment]
should this be changed throughout the tooling then @mirkobrombin ? or would you rather that be isolated to the update stacks command?  i would prefer the consistency of changing all of them, but there may be some show stoppers I'm unaware of

**Comment by mirkobrombin** [comment]
I would go the consistency way

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
